### ISSUE TITLE
1.4.2 Unbesetzte Rollen vertreten - Englischen Text entfernen

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution-5.0-GERMAN#1]
Hier ist noch der Originaltext drin geblieben. Bitte einmal löschen! 

**1.4.2 Unbesetzte Rollen vertreten**

> Whenever a Role in a Circle is unfilled, each Circle Lead is automatically considered a Role Lead of the unfilled Role.
> 
> When a Role is filled only by people who are not Partners of the Organization, then each Circle Lead is automatically considered a Role Lead of that Role as well. However, this default assignment only applies to the extent that the non-Partners are not actively fulfilling relevant responsibilities and duties that a Partner would hold.

Wann immer eine Rolle unbesetzt ist, gilt jede*r Kreis-Lead automatisch auch als ein*e Rollen-Lead der unbesetzten Rolle.

Wenn eine Rolle nur durch Personen ausgeübt wird, die keine Partner*innen der Organisation sind, dann wird jede*r Kreis-Lead automatisch auch als ein*e Rollen-Lead dieser Rolle betrachtet. Diese Standardzuweisung gilt jedoch nur in dem Maße, in dem die Nicht-Partner*innen die relevanten Verantwortlichkeiten und Pflichten nicht aktiv ausüben, die ein*e Partner*in halten würde.

**Comment by pscheuerer** [comment]
Danke @denniswittrock ! Dieser Issue ist behoben.
