### ISSUE TITLE
5.4.3 Meeting Prozess - Englischen Text entfernen

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution-5.0-GERMAN#2]
Hier müsste der Original-Text noch gelöscht werdne

**5.4.3 Meeting Prozess**

> The Facilitator must use the following process for Governance Meetings:
> 
> (a) Check-in Round: Each participant in turn shares their current state, or offers another opening comment for the meeting. Responses are not allowed.
> (b) Agenda Building & Processing: The Facilitator builds an agenda of Tensions to process, then processes each agenda item in turn.
> (c) Closing Round: Each participant in turn shares a closing reflection on the meeting. Responses are not allowed.
> At any point during this process, a participant may request a “Time Out” pause. The Facilitator may choose to grant or deny this request. During the Time Out, participants may discuss administrative issues or the rules of this Constitution. They may not use the Time Out to work towards the resolution of a Tension, Proposal, or Objection. The Facilitator may end a Time Out at any point and resume the normal meeting process.
> 
> A Policy of the Circle may add to this process, but may not conflict with any rules or requirements defined in this Article.
> 

Der*Die Prozessmoderator*in muss für Governance Meetings den folgenden Prozess verwenden:

(a) Check-in Runde: Alle Teilnehmenden äußern der Reihe nach ihr aktuelles Befinden, oder teilen einen anderen Wortbeitrag zur Eröffnung des Meetings. Reaktionen sind nicht erlaubt.
(b) Agenda-Erstellung & Verarbeitung: Der*Die Prozessmoderator*in erstellt eine Agenda aus zu verarbeitenden Spannungen und verarbeitet dann einen Agendapunkt nach dem anderen.
(c) Abschlussrunde: Alle Teilnehmenden teilen der Reihe nach ihre Abschlussreflektion über das Meeting. Reaktionen sind nicht erlaubt.
Ein*e Teilnehmer*in darf während dieses Prozesses jederzeit um eine „Auszeit“ [Time Out] Pause bitten. Der*Die Prozessmoderator*in darf entscheiden, ob er*sie diese Bitte gewährt oder ablehnt. Während der Auszeit dürfen die Teilnehmer*innen administrative Themen oder die Regeln dieser Verfassung diskutieren. Sie dürfen die Auszeit nicht nutzen, um auf die Klärung einer Spannung, eines Vorschlags oder eines Einwands hinzuarbeiten. Der*Die Prozessmoderator*in darf die Auszeit jederzeit beenden, und den normalen Meeting Prozess wieder aufnehmen.

Eine Richtlinie darf diesen Prozess ergänzen, darf jedoch nicht im Widerspruch zu irgendeiner Regel oder Anforderung stehen, die in diesem Artikel definiert ist.

**Comment by pscheuerer** [comment]
Danke für den Hinweis @denniswittrock. Dieser issue ist behoben.
