### ISSUE TITLE
5.5.2 Prozesswiederherstellung - Englischen Text entfernen

### ISSUE THREAD

**Issue by denniswittrock** [holacracyone/Holacracy-Constitution-5.0-GERMAN#3]
**5.5.2 Prozesswiederherstellung**

> Whenever an authorized party declares a Process Breakdown within a Circle, the following occurs:
> 
> (a) the Facilitator gains the authority to judge the logic and relevance of any arguments made to validate Proposals or Objections in the Circle; and
> (b) the Facilitator of the Super-Circle gains a Project to restore due-process within the Circle; and
> (c) the Facilitator of the Super-Circle gains the authority to take over as Facilitator or Secretary of the Circle; and
> (d) the Facilitator of the Super-Circle may assign an additional Circle Lead to the Circle for the duration of the Process Breakdown. Any decisions that person makes as Circle Lead supersede and prevent any conflicting decisions by another Circle Lead.
> These authorities end as soon as due process is restored in the Circle, as assessed by the Facilitator of the Super-Circle.
> 
> If the Circle in Process Breakdown has no Super-Circle, then the powers above all vest with its own Facilitator instead.

Wann immer eine befugte Partei ein Prozessversagen in einem Kreis erklärt, geschieht das Folgende:

(a) der*die Prozessmoderator*in erhält die Befugnis, Logik und Relevanz aller Argumente zu beurteilen, die gemacht wurden, um Vorschläge oder Einwände im Kreis geltend zu machen; und
(b) der*die Prozessmoderator*in des Super-Kreises erhält ein Projekt, das ordentliche Verfahren im Kreis wiederherzustellen; und
(c) der*die Prozessmoderator*in des Super-Kreises erhält die Befugnis, als Prozessmoderator*in oder Kreis-Sekretär*in des Kreises zu übernehmen; und
(d) der*die Prozessmoderator*in des Super-Kreises darf für die Dauer des Prozessversagens eine*n zusätzliche*n Kreis-Lead zuweisen. Alle Entscheidungen, die diese Person als Kreis-Lead trifft, übertrumpfen und verhindern alle widersprechenden Entscheidungen eines*r anderen Kreis-Lead*s.
Diese Befugnisse enden, sobald entsprechend der Einschätzung des*der Prozessmoderators*in des Super-Kreises das ordentliche Verfahren im Kreis wieder hergestellt ist.

Falls der Kreis, der sich im Prozessversagen befindet, keinen Super-Kreis hat, dann gehen stattdessen alle obigen Befugnisse auf seine*n eigene*n Prozessmoderator*in über.

**Comment by pscheuerer** [comment]
Dieser Issue ist behoben. Vielen Dank für den Hinweis @denniswittrock
